import type { Metadata } from "next";
import { Roboto, Open_Sans } from "next/font/google";
import "./globals.css";
import { LenisProvider } from "@/components/lenis-provider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const roboto = Roboto({
  weight: ["300", "400", "700", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "TheBitHQ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <LenisProvider
          options={{
            lerp: 0.1,
            wheelMultiplier: 0.8,
            smoothWheel: true,
          }}
        >
          <section className="relative">
            <Header />
            {children}
            <Footer />
          </section>
        </LenisProvider>
      </body>
    </html>
  );
}
